AllCops:
  DisplayCopNames: true
  ExtraDetails: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  Exclude:
    - bin/bundle
    - php_legacy/**/*

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/RescueStandardError:
  EnforcedStyle: implicit
